package cmd

import (
	"fmt"
	"net/url"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [url]",
	Short: "Generate a starter config file",
	Long:  "Print a starter YAML config file to stdout with sensible defaults for the given URL.",
	Args:  cobra.ExactArgs(1),
	RunE:  runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(_ *cobra.Command, args []string) error {
	rawURL := args[0]

	parsed, err := url.ParseRequestURI(rawURL)
	if err != nil {
		return fmt.Errorf("invalid URL %q: %w", rawURL, err)
	}

	// Derive a reasonable output directory name from the host.
	host := parsed.Hostname()
	host = strings.TrimPrefix(host, "www.")
	outputDir := "./" + strings.ReplaceAll(host, ".", "-") + "-docs"

	template := buildConfigTemplate(rawURL, outputDir)
	_, err = fmt.Fprint(os.Stdout, template)
	return err
}

// buildConfigTemplate returns a YAML config template string with the seed URL
// and output directory substituted in.
func buildConfigTemplate(seedURL, outputDir string) string {
	return fmt.Sprintf(`# docs-crawler configuration
# Generated by: docs-crawler init %s
#
# Edit the values below to customize the crawl behaviour.

source:
  url: %s

crawl:
  # Maximum link depth to follow (0 = unlimited).
  max_depth: 3
  # Number of concurrent fetch workers.
  workers: 10
  # Requests per second. 0 = auto-detect from response headers.
  rate_limit: 0
  # URL patterns to include (glob syntax). Empty means include all.
  includes: []
  # URL patterns to exclude (glob syntax).
  excludes:
    - "**/changelog/**"
    - "**/releases/**"
  # Set true to use headless Chrome for JavaScript-rendered pages.
  use_browser: false
  # Custom User-Agent string sent with every request.
  user_agent: "docs-crawler/0.1.0"
  # Per-request timeout in seconds.
  timeout_sec: 30
  # Set true to resume a previously interrupted crawl.
  resume: false

chunking:
  # Splitting strategy: "heading" (split at Markdown headings) or "fixed" (fixed token windows).
  strategy: heading
  # Maximum tokens per chunk.
  max_tokens: 512

embedding:
  # Embedder to use: auto, ollama, openai, cohere, tfidf.
  # "auto" probes for Ollama, then reads OPENAI_API_KEY / COHERE_API_KEY from env.
  embedder: auto
  # Model name (used by ollama / openai / cohere).
  model: nomic-embed-text
  # Batch size for embedding API calls.
  batch: 64

output:
  # Directory where Markdown files and index.db are written.
  dir: %s
  # Set true to enable debug-level logging.
  verbose: false
`, seedURL, seedURL, outputDir)
}
